# Generated by Django 5.1 on 2024-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0002_task_parent_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
