# Generated by Django 5.1 on 2024-10-14 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0003_project_slug_task_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="task",
            name="slug",
        ),
    ]
