# Generated by Django 5.1 on 2024-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0004_remove_project_slug_remove_task_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="progr",
            field=models.FloatField(default=0),
        ),
    ]
