# Generated by Django 5.1 on 2024-10-21 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0008_remove_project_tags_remove_task_tags_task_tag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="task",
            name="tag",
        ),
    ]
